import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/domain/shared/styles/globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { MuiThemeProvider } from "@/domain/shared/configs";
import { ReactNode } from "react";

const poppins = Poppins({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="__next" className={poppins.className}>
        <AppRouterCacheProvider options={{ key: "css" }}>
          <MuiThemeProvider>{children}</MuiThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
